const ADD_CARD = "ADD_CARD";
const ADD_CARD_SUCCESS = "ADD_CARD_SUCCESS";
const EDIT_CARD = "EDIT_CARD";
const FETCH_CARDS = "FETCH_CARDS";
const FETCH_CARDS_SUCCESS = "FETCH_CARDS_SUCCESS";
const FIND_CARD = "FIND_CARD";
const FIND_CARD_SUCCESS = "FIND_CARD_SUCCESS";
const FETCH_FIND_FAILURE = "FETCH_FIND_FAILURE";

const FETCH_CARD_TYPES = "FETCH_CARD_TYPES";
const FETCH_CARD_TYPES_SUCCESS = "FETCH_CARD_TYPES_SUCCESS";

export {
    ADD_CARD,
    ADD_CARD_SUCCESS,
    
    EDIT_CARD,
    
    FETCH_CARDS,
    FETCH_CARDS_SUCCESS,
    
    FIND_CARD,
    FIND_CARD_SUCCESS,

    FETCH_FIND_FAILURE,

    FETCH_CARD_TYPES,
    FETCH_CARD_TYPES_SUCCESS
};