const ADD_CREDIT_CARD = "ADD_CREDIT_CARD";
const EDIT_CREDIT_CARD = "EDIT_CREDIT_CARD";
const REQUEST_CARDS = "REQUEST_CARDS";
const RECEIVE_CARDS = "RECEIVE_CARDS";

export {
    ADD_CREDIT_CARD,
    EDIT_CREDIT_CARD,
    REQUEST_CARDS,
    RECEIVE_CARDS
};